version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
      - MONGO_INITDB_DATABASE=corespace
    ports:
      - 27017:27017
    volumes:
      - ./database/development/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongodb-express:
    image: mongo-express:latest
    container_name: mongodb-express
    restart: always
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=admin_password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - 8081:8081

  ms-service-handler:
    image: zombymediaic/ms-corespace:service-handler-1.1.0
    restart: always
    volumes:
      - ./container/service-handler/config.json:/service/config.json:ro
    depends_on:
      - mongodb-express
    environment:
      - MONGO_URL=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=corespace
      - MONGO_PASSWORD=masterpassword
      - MONGO_DB=corespace
      - ALLOW_DEBUG=true

  ms-register:
    image: zombymediaic/ms-corespace:register-1.1.0
    restart: always
    volumes:
      - ./container/register/config.json:/service/config.json:ro
    depends_on:
      - ms-service-handler
    ports:
      - 3001:3001
    environment:
      - MONGO_URL=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=corespace
      - MONGO_PASSWORD=masterpassword
      - MONGO_DB=corespace
      - ALLOW_DEBUG=true
      - PORT=3001

  ms-login:
    image: zombymediaic/ms-corespace:login-1.1.0
    restart: always
    volumes:
      - ./container/login/config.json:/service/config.json:ro
    depends_on:
      - ms-service-handler
    ports:
      - 3002:3002
    environment:
      - MONGO_URL=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=corespace
      - MONGO_PASSWORD=masterpassword
      - MONGO_DB=corespace
      - ALLOW_DEBUG=true
      - PORT=3002